//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3tr0viCh.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3tr0viCh.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER={0};PORT={1};DATABASE={2};USER={3};PASSWORD={4};.
        /// </summary>
        internal static string ConnectionFireBird {
            get {
                return ResourceManager.GetString("ConnectionFireBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER={0};PORT={1};DATABASE={2};USER={3};PASSWORD={4};.
        /// </summary>
        internal static string ConnectionStringMySql {
            get {
                return ResourceManager.GetString("ConnectionStringMySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; not exists or path empty..
        /// </summary>
        internal static string ExceptionDirectoryNotExists {
            get {
                return ResourceManager.GetString("ExceptionDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not exists or path empty..
        /// </summary>
        internal static string ExceptionFileNotExists {
            get {
                return ResourceManager.GetString("ExceptionFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FrmAboutBtnOk {
            get {
                return ResourceManager.GetString("FrmAboutBtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string FrmAboutCaption {
            get {
                return ResourceManager.GetString("FrmAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Распространяется свободно (FREEWARE)..
        /// </summary>
        internal static string FrmAboutEULA_1_1 {
            get {
                return ResourceManager.GetString("FrmAboutEULA_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • ЗАПРЕЩЕНО использование программы в коммерческих целях без согласования с автором..
        /// </summary>
        internal static string FrmAboutEULA_1_2 {
            get {
                return ResourceManager.GetString("FrmAboutEULA_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • ЗАПРЕЩЕНО распространение программы в коммерческих целях без согласования с автором..
        /// </summary>
        internal static string FrmAboutEULA_2 {
            get {
                return ResourceManager.GetString("FrmAboutEULA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • ЗАПРЕЩЕНО любое изменение, адаптирование, перевод, дизассемблирование данной программы..
        /// </summary>
        internal static string FrmAboutEULA_3 {
            get {
                return ResourceManager.GetString("FrmAboutEULA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Поставляется «КАК ЕСТЬ», то есть автор не даёт никаких гарантий работоспособности программы, а также не несёт никакой ответственности за любой прямой, косвенный или иной ущерб, понесённый в результате её использования.
        ///Вы используете это программное обеспечение на свой риск..
        /// </summary>
        internal static string FrmAboutEULA_4 {
            get {
                return ResourceManager.GetString("FrmAboutEULA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия {0}.
        /// </summary>
        internal static string FrmAboutVersion {
            get {
                return ResourceManager.GetString("FrmAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string LogExt {
            get {
                return ResourceManager.GetString("LogExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd_HH-mm-ss.
        /// </summary>
        internal static string LogFormatDateTimeFile {
            get {
                return ResourceManager.GetString("LogFormatDateTimeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        internal static string LogFormatDateTimeText {
            get {
                return ResourceManager.GetString("LogFormatDateTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: close ({1}).
        /// </summary>
        internal static string LogFormClose {
            get {
                return ResourceManager.GetString("LogFormClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: open.
        /// </summary>
        internal static string LogFormOpen {
            get {
                return ResourceManager.GetString("LogFormOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt;&gt;&gt;&gt;&gt; START PROGRAM {0} {1}.
        /// </summary>
        internal static string LogProgramStart {
            get {
                return ResourceManager.GetString("LogProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;&lt;&lt;&lt;&lt;&lt; STOP PROGRAM.
        /// </summary>
        internal static string LogProgramStop {
            get {
                return ResourceManager.GetString("LogProgramStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.
        /// </summary>
        internal static string LogSubDirectory {
            get {
                return ResourceManager.GetString("LogSubDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string TextInputBoxBtnCancel {
            get {
                return ResourceManager.GetString("TextInputBoxBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TextInputBoxBtnOk {
            get {
                return ResourceManager.GetString("TextInputBoxBtnOk", resourceCulture);
            }
        }
    }
}
