//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3tr0viCh.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3tr0viCh.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string FrmAboutCaption {
            get {
                return ResourceManager.GetString("FrmAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия {0}.
        /// </summary>
        internal static string FrmAboutVersion {
            get {
                return ResourceManager.GetString("FrmAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string LogExt {
            get {
                return ResourceManager.GetString("LogExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd_HH-mm-ss.
        /// </summary>
        internal static string LogFormatDateTimeFile {
            get {
                return ResourceManager.GetString("LogFormatDateTimeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.fff.
        /// </summary>
        internal static string LogFormatDateTimeText {
            get {
                return ResourceManager.GetString("LogFormatDateTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: close ({1}).
        /// </summary>
        internal static string LogFormClose {
            get {
                return ResourceManager.GetString("LogFormClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: open.
        /// </summary>
        internal static string LogFormOpen {
            get {
                return ResourceManager.GetString("LogFormOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt;&gt;&gt;&gt;&gt; START PROGRAM {0} {1}.
        /// </summary>
        internal static string LogProgramStart {
            get {
                return ResourceManager.GetString("LogProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;&lt;&lt;&lt;&lt;&lt; STOP PROGRAM.
        /// </summary>
        internal static string LogProgramStop {
            get {
                return ResourceManager.GetString("LogProgramStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.
        /// </summary>
        internal static string LogSubDirectory {
            get {
                return ResourceManager.GetString("LogSubDirectory", resourceCulture);
            }
        }
    }
}
